# Generated by Django 5.1.7 on 2025-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("D", "Dízimo"), ("O", "Oferta"), ("S", "Despesa")],
                        max_length=1,
                    ),
                ),
                ("quantia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
                ("descricao", models.TextField(blank=True, null=True)),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "culto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CV", "Culto da Vitória"),
                            ("EBD", "EBD"),
                            ("GR", "Gratidão"),
                            ("LR", "Lar"),
                            ("FM", "Família"),
                            ("DP", "Departamento"),
                            ("OT", "Outro"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "tipo_despesa",
                    models.CharField(
                        blank=True,
                        choices=[("CT", "Conta"), ("IN", "Insumo"), ("OT", "Outro")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("mes", models.IntegerField(default=1)),
                ("ano", models.IntegerField(default=2025)),
            ],
            options={
                "db_table": "transacoes",
            },
        ),
    ]
