# Generated by Django 5.1.7 on 2025-03-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transacao",
            old_name="valor",
            new_name="quantia",
        ),
        migrations.AddField(
            model_name="transacao",
            name="culto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CV", "Culto da Vitória"),
                    ("EBD", "EBD"),
                    ("GR", "Gratidão"),
                    ("LR", "Lar"),
                    ("FM", "Família"),
                    ("DP", "Departamento"),
                    ("OT", "Outro"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transacao",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transacao",
            name="tipo_despesa",
            field=models.CharField(
                blank=True,
                choices=[("CT", "Conta"), ("IN", "Insumo"), ("OT", "Outro")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="data",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="tipo",
            field=models.CharField(
                choices=[("D", "Dízimo"), ("O", "Oferta"), ("S", "Despesa")],
                max_length=1,
            ),
        ),
    ]
