# Generated by Django 5.1.7 on 2025-03-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_rename_valor_transacao_quantia_transacao_culto_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transacao",
            table="finance_transacao",
        ),
    ]
