# Generated by Django 5.1.7 on 2025-04-30 15:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_relatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='caminho_arquivo',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='relatorios/'),
        ),
    ]
