# Generated by Django 5.1.7 on 2025-05-15 14:30

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_relatorio_caminho_arquivo_relatorio_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lider', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(default='', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='relatorios/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='finance.igreja'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='finance.igreja'),
        ),
    ]
