# Generated by Django 5.1.7 on 2025-05-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='discriminacao',
            field=models.CharField(blank=True, help_text='Discriminação digitada no PDF interativo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='manual',
            field=models.BooleanField(default=False, help_text='Transação preenchida manualmente pelo PDF interativo'),
        ),
    ]
