# Generated by Django 5.1.7 on 2025-10-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_saldomensal_data_fechamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaldoMensal',
        ),
    ]
