# Generated by Django 5.1.7 on 2025-10-30 16:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_add_drive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='relatorios/'),
        ),
    ]
